import streamlit as st

def app():
    st.title("About Alzheimer Disease")
    st.markdown("<p style='color: white; text-align: left;'>Alzheimer's disease is a progressive neurological disorder that affects the brain and results in the decline of cognitive function, memory loss, and behavioral changes. It is the most common cause of dementia, accounting for approximately 60-80% of cases.</p>", unsafe_allow_html=True)
    st.markdown("<p style='color: white; text-align: left;'>The disease is characterized by the formation of abnormal protein deposits in the brain, called amyloid plaques and tau tangles, which damage and eventually kill nerve cells. This causes the brain to shrink and leads to a decline in mental and physical abilities.</p>", unsafe_allow_html=True)
    st.markdown("<p style='color: white; text-align: left;'>The symptoms of Alzheimer's disease typically begin with mild memory loss and gradually progress to include confusion, difficulty with language, poor judgment, mood swings, and a loss of motivation. As the disease advances, individuals with Alzheimer's may require assistance with daily tasks such as eating, dressing, and personal hygiene.</p>", unsafe_allow_html=True)
    st.markdown("<p style='color: white; text-align: left;'>The exact cause of Alzheimer's disease is not yet fully understood, but there are several risk factors that have been identified. These include age, genetics, lifestyle factors such as diet and exercise, and other medical conditions such as high blood pressure and diabetes.</p>", unsafe_allow_html=True)
    st.markdown("<p style='color: white; text-align: left;'>While there is currently no cure for Alzheimer's disease, there are medications that can help manage some of the symptoms and slow the progression of the disease in some cases. Additionally, there are lifestyle interventions, such as exercise and a healthy diet, that may help reduce the risk of developing Alzheimer's disease. Research is ongoing to better understand the disease and develop more effective treatments.</p>", unsafe_allow_html=True)
